ifeq (,$(findstring msvc,$(platform)))
CORE_DEFINE := -Dstricmp=strcasecmp -Dstrnicmp=strncasecmp
else
CORE_DEFINE :=
endif
SOURCES_C   := $(CORE_DIR)/libretro.c \
                $(CORE_DIR)/gfx.c \
                $(CORE_DIR)/interrpt.c \
                $(CORE_DIR)/main.c \
                $(CORE_DIR)/network.c \
                $(CORE_DIR)/input.c \
                $(CORE_DIR)/dj.c \
                $(CORE_DIR)/menu.c \
                $(CORE_DIR)/micromod.c
